openapi: "3.0.0"
info:
  title: Zero Type Demo
  version: v1

paths:
  /omit/empty:
    post:
      summary: Show go zero value problem
      operationId: omitEmpty
      tags:
      - go
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ZeroTypes'
      responses:
        200:
          description: Should respond with what you send
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZeroTypes'

components:
  schemas:
    ZeroTypes:
      type: object
      properties:
        emptyString:
          type: string
        falseBool:
          type: boolean
        zeroInt:
          type: integer
