/*
 * Zero Type Demo
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ZeroTypes struct for ZeroTypes
type ZeroTypes struct {
	EmptyString string `json:"emptyString,omitempty"`
	FalseBool bool `json:"falseBool,omitempty"`
	ZeroInt int32 `json:"zeroInt,omitempty"`
}
